AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS account observability stack

Parameters:
  AwsOrgId:
    Type: String
  AwsOrgRootId:
    Type: String
  TargetRegions:
    Type: String
  ManagementOu:
    Type: String
  ObservabilityOu:
    Type: String
  DatadogSite:
    Type: String
  DatadogApiKey:
    Type: String
    NoEcho: 'true'
  DatadogAppKey:
    Type: String
    NoEcho: 'true'
  DataDogLogsDestinationArn:
    Type: String
    NoEcho: 'true'
  AwsOamSinkArn:
    Type: String

Resources:
  DatadogIntegrationStackSet:
    Type: AWS::Serverless::Application
    Properties:
      Location: "./stacksets/datadog-integration/stackset.yaml"
      Parameters:
        DeploymentOrgId: !Ref AwsOrgRootId
        TargetRegions: !Ref TargetRegions
        DatadogApiKey: !Ref DatadogApiKey
        DatadogAppKey: !Ref DatadogAppKey
        DatadogSite: !Ref DatadogSite
        DisableMetricCollection: 'true'

  LogShippingStackSet:
    Type: AWS::Serverless::Application
    DependsOn:
      - DatadogShippingStackSet
    Properties:
      Location: "./stacksets/logging/stackset.yaml"
      Parameters:
        DestinationArn: !Ref DataDogLogsDestinationArn
        DeploymentOrgId: !Ref AwsOrgRootId
        TargetRegions: !Ref TargetRegions

  CwCrossAccountShareStackSet:
    Type: AWS::Serverless::Application
    Properties:
      Location: "./stacksets/metrics/stackset.yaml"
      Parameters:
        DeploymentOrgId: !Ref AwsOrgRootId
        TargetRegions: !Ref TargetRegions
        AwsOamSinkArn: !Ref AwsOamSinkArn
        CrossAccountSharingPolicy: View-Access-for-all-services
        MonitoringAccountId: !Select [ "4", !Split [ ":", !Ref AwsOamSinkArn ] ]
        ObservabilityOuPath: !Sub "${AwsOrgId}/${AwsOrgRootId}/${ManagementOu}/${ObservabilityOu}"
