AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS account observability stack

Parameters:
  AwsOrgId:
    Type: String
  AwsOrgRootId:
    Type: String
  TargetRegions:
    Type: String
    Description: List of OUs
  ObservabilityOu:
    Type: String
    Description: OU of observability accounts
  DatadogHttpEndpointUrl:
    Type: String
  DatadogApiKey:
    Type: String
    NoEcho: 'true'

Resources:

  DatadogShippingStackSet:
    Type: AWS::Serverless::Application
    Properties:
      Location: "./stacksets/datadog-shipping/stackset.yaml"
      Parameters:
        AwsOrgId: !Ref AwsOrgId
        ObservabilityOu: !Ref ObservabilityOu
        TargetRegions: !Ref TargetRegions
        DatadogHttpEndpointUrl: !Ref DatadogHttpEndpointUrl
        DatadogApiKey: !Ref DatadogApiKey
