AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS account observability stack

Parameters:
  AwsOrgId:
    Type: String
  AwsOrgRootId:
    Type: String
  TargetRegions:
    Type: String
  ObservabilityOu:
    Type: String
  DatadogSite:
    Type: String
  DatadogApiKey:
    Type: String
    NoEcho: 'true'
  DatadogAppKey:
    Type: String
    NoEcho: 'true'
  DataDogLogsDestinationArn:
    Type: String
    NoEcho: 'true'
  AwsOamSinkArn:
    Type: String

Resources:
  DatadogIntegrationStackSet:
    Type: AWS::Serverless::Application
    Properties:
      Location: "./stacksets/datadog-integration/stackset.yaml"
      Parameters:
        DeploymentOrgId: !Ref AwsOrgRootId
        TargetRegions: !Ref TargetRegions
        DatadogApiKey: !Ref DatadogApiKey
        DatadogAppKey: !Ref DatadogAppKey
        DatadogSite: !Ref DatadogSite
  
  DatadogIntegrationManagementStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: "https://datadog-cloudformation-template.s3.amazonaws.com/aws/main_organizations.yaml"
      Parameters:
        DatadogApiKey: !Ref DatadogApiKey
        DatadogAppKey: !Ref DatadogAppKey
        DatadogSite: !Ref DatadogSite

  DatadogShippingStackSet:
    Type: AWS::Serverless::Application
    Properties:
      Location: "./stacksets/datadog-shipping/stackset.yaml"
      Parameters:
        AwsOrgId: !Ref AwsOrgId
        ObservabilityOu: !Ref ObservabilityOu
        TargetRegions: !Ref TargetRegions
        DatadogSite: !Ref DatadogSite
        DatadogApiKey: !Ref DatadogApiKey

  LogShippingStackSet:
    Type: AWS::Serverless::Application
    DependsOn:
      - DatadogShippingStackSet
    Properties:
      Location: "./stacksets/logging/stackset.yaml"
      Parameters:
        DestinationArn: !Ref DataDogLogsDestinationArn
        DeploymentOrgId: !Ref AwsOrgRootId
        TargetRegions: !Ref TargetRegions

  LogShippingManagementStack:
    Type: AWS::Serverless::Application
    DependsOn:
      - DatadogShippingStackSet
    Properties:
      Location: "./stacksets/logging/template.yaml"
      Parameters:
        DestinationArn: !Ref DataDogLogsDestinationArn

  MetricsSinkManagementStack:
    Type: AWS::Serverless::Application
    DependsOn:
      - DatadogShippingStackSet
    Properties:
      Location: "./stacksets/metrics/template.yaml"
      Parameters:
        AwsOamSinkArn: !Ref AwsOamSinkArn

