Metadata:
  localTemplateFile: &template_body ./template.yaml

AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS account infrastructure stackset (datadog logging)

Parameters:
  DestinationArn:
    Type: String
  DeploymentOrgId:
    Type: CommaDelimitedList
  TargetRegions:
    Type: CommaDelimitedList

Resources:
  DatadogLogShippingStackSet:
    Type: AWS::CloudFormation::StackSet
    Properties:
      StackSetName: DatadogLogging
      Description: Datadog logging
      Parameters:
        - ParameterKey: DestinationArn
          ParameterValue: !Ref DestinationArn
      Capabilities:
        - CAPABILITY_IAM
      StackInstancesGroup:
        - DeploymentTargets:
            OrganizationalUnitIds: !Ref DeploymentOrgId
          Regions: !Ref TargetRegions
      AutoDeployment:
        Enabled: true
        RetainStacksOnAccountRemoval: false
      ManagedExecution:
        Active: true
      OperationPreferences:
        RegionConcurrencyType: PARALLEL
        FailureToleranceCount: 1
        MaxConcurrentCount: 5
      PermissionModel: SERVICE_MANAGED
      TemplateBody: *template_body
