Metadata:
  OamLink:
    localTemplateFile: &oam_link_template_body ./oam-link-template.yaml
  CrossAccountSharing:
    localTemplateFile: &cross_account_sharing_template_body ./cw-cross-account-sharing-template.yaml

AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS account infrastructure stackset (Metrics)

Parameters:
  DeploymentOrgId:
    Type: CommaDelimitedList
    Description: Derployment org IDs
  TargetRegions:
    Type: CommaDelimitedList
    Description: Regions to deploy to
  AwsOamSinkArn:
    Type: String
    Description: ARN of CW OAM Sink
  CrossAccountSharingPolicy:
    Type: String
    Description: Name of cross-account policy used in cross-account share stack
  MonitoringAccountId:
    Description: ID of monitoring account
    Type: String
  ObservabilityOuPath:
    Type: String
    Description: OU of observability accounts

Resources:
  CloudWatchOamLinkStackSet:
    Type: AWS::CloudFormation::StackSet
    Properties:
      StackSetName: CloudWatchOamLink
      Description: CloudWatch OAM Link
      Parameters:
        - ParameterKey: AwsOamSinkArn
          ParameterValue: !Ref AwsOamSinkArn
      StackInstancesGroup:
        - DeploymentTargets:
            OrganizationalUnitIds: !Ref DeploymentOrgId
          Regions: !Ref TargetRegions
      AutoDeployment:
        Enabled: true
        RetainStacksOnAccountRemoval: false
      ManagedExecution:
        Active: true
      OperationPreferences:
        RegionConcurrencyType: PARALLEL
        FailureToleranceCount: 1
        MaxConcurrentCount: 5
      PermissionModel: SERVICE_MANAGED
      TemplateBody: *oam_link_template_body

  CloudWatcCrossAccountShareStackSet:
    Type: AWS::CloudFormation::StackSet
    Properties:
      StackSetName: CloudWatchCrossAccountShare
      Description: CloudWatch cross-account sharing
      Parameters:
        - ParameterKey: ObservabilityOuPath
          ParameterValue:  !Ref ObservabilityOuPath
        - ParameterKey: MonitoringAccountId
          ParameterValue:  !Ref MonitoringAccountId
        - ParameterKey: Policy
          ParameterValue: !Ref CrossAccountSharingPolicy
      StackInstancesGroup:
        - DeploymentTargets:
            OrganizationalUnitIds: !Ref DeploymentOrgId
          Regions: !Ref TargetRegions
      Capabilities:
        - CAPABILITY_IAM
        - CAPABILITY_NAMED_IAM
      AutoDeployment:
        Enabled: true
        RetainStacksOnAccountRemoval: false
      ManagedExecution:
        Active: true
      OperationPreferences:
        RegionConcurrencyType: PARALLEL
        FailureToleranceCount: 1
        MaxConcurrentCount: 5
      PermissionModel: SERVICE_MANAGED
      TemplateBody: *cross_account_sharing_template_body
