AWSTemplateFormatVersion: '2010-09-09'
Description: AWS CloudWatch OAM Sink

Parameters:
  AwsOamSinkArn:
    Type: String
    Description: ARN of CW OAM Sink

Conditions:
  SkipSinkAccount: !Not [
    !Equals [
      !Ref AWS::AccountId, !Select [
        "4", !Split [
          ":", !Ref AwsOamSinkArn]
        ]
      ]
    ]

Resources:
  OamLink:
    Type: AWS::Oam::Link
    Condition: SkipSinkAccount
    Properties:
      LabelTemplate: "$AccountName"
      ResourceTypes:
        - AWS::CloudWatch::Metric
        - AWS::XRay::Trace
        - AWS::ApplicationInsights::Application
        - AWS::InternetMonitor::Monitor
        # No need because we handle cross-account logs to Datadog via firehose
        #- AWS::Logs::LogGroup
      SinkIdentifier: !Ref AwsOamSinkArn
