Metadata:
  DatadogLogShipping:
    localTemplateFile: &dd_logs_template_body ./logs-template.yaml
  DatadogMetricsShipping:
    localTemplateFile: &dd_metrics_template_body ./metrics-stream-template.yaml
  DatadogMetricsSink:
    localTemplateFile: &dd_metrics_sink_body ./metrics-sink-template.yaml

AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS account infrastructure stackset (datadog log shipping)

Parameters:
  AwsOrgId:
    Type: String
    Description: AWS Organization ID
  ObservabilityOu:
    Type: CommaDelimitedList
    Description: List of OUs
  TargetRegions:
    Type: CommaDelimitedList
    Description: Regions to deploy to
  DatadogSite:
    Type: String
  DatadogApiKey:
    Type: String
    NoEcho: 'true'

Resources:
  DatadogLogShippingStackSet:
    Type: AWS::CloudFormation::StackSet
    Properties:
      StackSetName: DatadogLogShipping
      Description: Datadog log shipping
      Parameters:
        - ParameterKey: DatadogSite
          ParameterValue: !Ref DatadogSite
        - ParameterKey: DatadogAPIKey
          ParameterValue: !Ref DatadogApiKey
        - ParameterKey: AwsOrgId
          ParameterValue: !Ref AwsOrgId
      Capabilities:
        - CAPABILITY_IAM
      StackInstancesGroup:
        - DeploymentTargets:
            OrganizationalUnitIds: !Ref ObservabilityOu
          Regions: !Ref TargetRegions
      AutoDeployment:
        Enabled: true
        RetainStacksOnAccountRemoval: false
      ManagedExecution:
        Active: true
      OperationPreferences:
        RegionConcurrencyType: PARALLEL
        FailureToleranceCount: 1
        MaxConcurrentCount: 5
      PermissionModel: SERVICE_MANAGED
      TemplateBody: *dd_logs_template_body

  DatadogStreamStackSet:
    Type: AWS::CloudFormation::StackSet
    Properties:
      StackSetName: DatadogMetricsStreams
      Description: Datadog metrics stream
      Parameters:
        - ParameterKey: DatadogApiKey
          ParameterValue: !Ref DatadogApiKey
        - ParameterKey: DatadogSite
          ParameterValue: !Ref DatadogSite
        - ParameterKey: FilterMethod
          ParameterValue: 'NONE'
        - ParameterKey: FirstNamespace
          ParameterValue: ''
        - ParameterKey: SecondNamespace
          ParameterValue: ''
        - ParameterKey: ThirdNamespace
          ParameterValue: ''
      Capabilities:
        - CAPABILITY_IAM
      StackInstancesGroup:
        - DeploymentTargets:
            OrganizationalUnitIds: !Ref ObservabilityOu
          Regions: !Ref TargetRegions
      AutoDeployment:
        Enabled: true
        RetainStacksOnAccountRemoval: false
      ManagedExecution:
        Active: true
      OperationPreferences:
        RegionConcurrencyType: PARALLEL
        FailureToleranceCount: 1
        MaxConcurrentCount: 5
      PermissionModel: SERVICE_MANAGED
      TemplateBody: *dd_metrics_template_body

  DatadogMetricsSinkStackSet:
    Type: AWS::CloudFormation::StackSet
    Properties:
      StackSetName: CloudWatchMetricsSink
      Description: CloudWatch metrics cross-account sink
      Parameters:
        - ParameterKey: AwsOrgId
          ParameterValue: !Ref AwsOrgId
      Capabilities:
        - CAPABILITY_IAM
      StackInstancesGroup:
        - DeploymentTargets:
            OrganizationalUnitIds: !Ref ObservabilityOu
          Regions: !Ref TargetRegions
      AutoDeployment:
        Enabled: true
        RetainStacksOnAccountRemoval: false
      ManagedExecution:
        Active: true
      OperationPreferences:
        RegionConcurrencyType: PARALLEL
        FailureToleranceCount: 1
        MaxConcurrentCount: 5
      PermissionModel: SERVICE_MANAGED
      TemplateBody: *dd_metrics_sink_body
