Metadata:
  DatadogLogShipping:
    localTemplateFile: &dd_logs_template_body ./logs-template.yaml

AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS account infrastructure stackset (datadog)

Parameters:
  AwsOrgId:
    Type: String
    Description: AWS Organization ID
  ObservabilityOu:
    Type: CommaDelimitedList
    Description: List of OUs
  TargetRegions:
    Type: CommaDelimitedList
    Description: Regions to deploy to
  DatadogHttpEndpointUrl:
    Type: String
  DatadogApiKey:
    Type: String
    NoEcho: 'true'

Resources:
  DatadogLogShippingStackSet:
    Type: AWS::CloudFormation::StackSet
    Properties:
      StackSetName: DatadogLogShipping
      Description: Datadog log shipping
      Parameters:
        - ParameterKey: DatadogHttpEndpointUrl
          ParameterValue: !Ref DatadogHttpEndpointUrl
        - ParameterKey: DatadogAPIKey
          ParameterValue: !Ref DatadogApiKey
        - ParameterKey: AwsOrgId
          ParameterValue: !Ref AwsOrgId
      Capabilities:
        - CAPABILITY_IAM
      StackInstancesGroup:
        - DeploymentTargets:
            OrganizationalUnitIds: !Ref ObservabilityOu
          Regions: !Ref TargetRegions
      AutoDeployment:
        Enabled: true
        RetainStacksOnAccountRemoval: false
      ManagedExecution:
        Active: true
      OperationPreferences:
        RegionConcurrencyType: PARALLEL
        FailureToleranceCount: 1
        MaxConcurrentCount: 5
      PermissionModel: SERVICE_MANAGED
      TemplateBody: *dd_logs_template_body
