AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS account infrastructure stackset (datadog integration)

Parameters:
  DeploymentOrgId:
    Type: CommaDelimitedList
  TargetRegions:
    Type: CommaDelimitedList
  DatadogSite:
    Type: String
  DatadogApiKey:
    Type: String
    NoEcho: 'true'
  DatadogAppKey:
    Type: String
    NoEcho: 'true'

Resources:
  DatadogLogShippingStackSet:
    Type: AWS::CloudFormation::StackSet
    Properties:
      StackSetName: DatadogIntegration
      Description: Datadog integration
      Parameters:
        - ParameterKey: DatadogSite
          ParameterValue: !Ref DatadogSite
        - ParameterKey: DatadogApiKey
          ParameterValue: !Ref DatadogApiKey
        - ParameterKey: DatadogAppKey
          ParameterValue: !Ref DatadogAppKey
      Capabilities:
        - CAPABILITY_IAM
        - CAPABILITY_NAMED_IAM
      StackInstancesGroup:
        - DeploymentTargets:
            OrganizationalUnitIds: !Ref DeploymentOrgId
          Regions: !Ref TargetRegions
      AutoDeployment:
        Enabled: true
        RetainStacksOnAccountRemoval: false
      ManagedExecution:
        Active: true
      OperationPreferences:
        RegionConcurrencyType: PARALLEL
        FailureToleranceCount: 1
        MaxConcurrentCount: 5
      PermissionModel: SERVICE_MANAGED
      TemplateURL: https://datadog-cloudformation-template.s3.amazonaws.com/aws/main_organizations.yaml
